platform :ios, '10.0'

target 'LeoExample' do
  use_frameworks!

  # General
  pod 'BaseCoordinator', '~> 1.0'
  
  # Networking
  pod 'LEONetworkLayer', :path => '../'

  # Helpers
  pod 'KeychainSwift', '~> 16.0'

end
